repo_url: https://github.com/OUXT-Polaris/polaris.git
site_name: Polaris Documentation.
site_description: Documentation of Polaris, "Policy and Object map description Language for Automated Robot Intelligence with Semantic Behavior"
site_author: Masaya Kataoka
markdown_extensions:
  - toc:
      permalink: '#'
theme: 
  name: material
  feature:
    tabs: true
  palette:
    primary: blue
    accent: lime
    scheme: slate
  icon:
    logo: material/robot
    repo: fontawesome/brands/github
plugins:
  - search