name: Documentation

on:
  schedule:
    - cron: 0 0 * * *
  push:

jobs:
    job1:
        name: Generate Documentation
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v2-beta
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.6.12'
        - name: Install 
          run: |
            cd docs
            pip3 install -r requirements.txt
        # - name: Install doxygen/depends of doxybook
        #  run: sudo apt install -y doxygen wget
        #- name: Wget package
        #  run: |
        #    wget https://github.com/matusnovak/doxybook2/releases/download/v1.2.3/doxybook2-linux-amd64-v1.2.3.zip
        #    mkdir -p ~/doxybook2
        #    cp -rf . ~/doxybook2
        #    cd ~/doxybook2
        #    unzip doxybook2-linux-amd64-v1.2.3.zip
        - name: Build documentation
          run: |
            cd docs
            mkdocs build
        - name: 'Upload Artifact'
          uses: actions/upload-artifact@v2
          with:
            name: html
            path: docs/site
            retention-days: 1